CREATE DATABASE IF NOT EXISTS php_pro
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE php_pro;

CREATE TABLE IF NOT EXISTS users (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   avatar VARCHAR(255),
   phone_number VARCHAR(20),
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   is_active BOOLEAN NOT NULL DEFAULT TRUE,
   last_login_at TIMESTAMP
);
